# Generated by Django 5.1.5 on 2025-02-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_field',
        ),
    ]
